# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*.*.*-release'
      - 'v*.*.*-master'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup & Build
        run: |
          cd ProjectSource
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Package
        run: |
          cd ProjectSource/build
          tar czf lbm-linux-Release-${GITHUB_REF_NAME}.tar.gz executables

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ProjectSource/build/lbm-linux-Release-${GITHUB_REF_NAME}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}