name: Release

on:
  push:
    tags:
      - 'v*.*.*-release'
      - 'v*.*.*-master'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version tag
        id: get_tag
        run: echo "GIT_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Setup & Build
        run: |
          cd ProjectSource
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DGIT_TAG=${{ env.GIT_TAG }}
          cmake --build build --config Release

      - name: Package
        run: |
          cd ProjectSource/build
          mkdir -p package
          cp executables package/
          cp version.info package/
          
          tar czf "lbm-linux-Release-${{ env.GIT_TAG }}.tar.gz" -C package .
          cp "lbm-linux-Release-${{ env.GIT_TAG }}.tar.gz" "lbm-linux-latest.tar.gz"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            projectSource/build/lbm-linux-Release-${GITHUB_REF_NAME}.tar.gz
            ProjectSource/build/lbm-linux-latest.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}